export const NOTIFICATION_TEACHER = 0;
export const NOTIFICATION_STUDENT = 1;

export const NOTIFICATION_PURCHASE_COURSE_STUDENT =
    "NOTIFICATION_PURCHASE_COURSE_STUDENT";

export const NOTIFICATION_PURCHASE_COURSE_INSTRUCTOR =
    "NOTIFICATION_PURCHASE_COURSE_INSTRUCTOR";

export enum NotificationType {
    INSTRUCTOR = "INSTRUCTOR",
    STUDENT = "STUDENT",
}
